### ISSUE TITLE
I can't import the module installed with pip.

### ISSUE THREAD

**Issue by BMaxV** [dhermes/bezier#23]
Title. Or it takes an unreasonable amount of time. Either way it's not useable as it is.

**Comment by dhermes** [comment]
@BMaxV Thanks for filing! I'm happy you found my little library and sorry the install failed for you.

I'd love to help you get it installed.

1. What operating system are you using?
1. What command are you using to install? (I assume `pip install bezier`)
1. Is there any error output when installing or does it work just fine?
1. Is there any error output when the import stalls?

**Comment by BMaxV** [comment]
I am running xubuntu / ubuntu 16.04.

I used "pip install bezier" to install.

There was no error output when installing.

There is no error when the import stalls and actually after trying it again it seems fine.

So apparently a restart fixed the problem.

Now I feel a bit stupid for creating this ticket, but maybe someone else has problems after installing and immediately running it so it's fine? Anyway, thanks for helping so quickly!

**Comment by dhermes** [comment]
That's great to hear it's working for you! I also run Ubuntu 16.04 and haven't experienced issues. Maybe it was some random page failure when reading the modules from disk?

----

BTW if you install from `master`:

```
pip install https://github.com/dhermes/bezier
```

the latest version has Fortran speedups that are considerably faster for many operations. I haven't made a new release yet because I'm "struggling" with building the Fortran extensions on Windows.
