### ISSUE TITLE
Problem installing libbezier

### ISSUE THREAD

**Issue by gabrielndluna** [dhermes/bezier#268]
I need to install the library bezier 2020.5.19, trying to install it with setup.py I had the problem "The BEZIER_INSTALL_PREFIX environment variable must be set."
I tried to install libbezier but I can't figure out how to do it. 
I read the steps stated in https://bezier.readthedocs.io/en/2020.5.19/abi/installation.html but I cannot continue when I install the recommended "CMake" because I do not clearly understand how to proceed.
I do not know if this is common knowledge but I am lost here.

Thanks in advance for the help!

Also: it seems that just typing "python  -m install setup.py --no-binary=bezier" does not work in this specific version I need. Because when I pip install using the specification I end up with bezier 2020.1.14

**Comment by dhermes** [comment]
A few questions:

- Do you need to install from source? (i.e. why are you using `setup.py` / dealing with `BEZIER_INSTALL_PREFIX`)
- What OS are you running?
- Have you tried `pip install 'bezier==2020.5.19'`

**Comment by gabrielndluna** [comment]
I ran "python -m pip install bezier==2020.5.19 --no-binary=bezier"
And I encountered two errors: 

1.  The BEZIER_INSTALL_PREFIX environment variable must be set.
2.  ERROR: No matching distribution found for bezier==2020.5.19
![Errors when pip installing](https://user-images.githubusercontent.com/88359585/128651900-855c6748-a274-46f5-a48b-4e3180f74715.PNG)

I downloaded from the source to avoid the second error.

I am using windows 10, and python 3.9.

**Comment by dhermes** [comment]
Ah I see, from https://bezier.readthedocs.io/en/2020.5.19/index.html, look for "To install a pure Python version (i.e. with no binary extension):" and you'll see

```
$ BEZIER_NO_EXTENSION=true \
>   python  -m pip install --upgrade bezier --no-binary=bezier
```

In particular, note that you are leaving out the `BEZIER_NO_EXTENSION=true` when doing this, which is why you are getitng errors about `BEZIER_INSTALL_PREFIX`.

---

Is there a reason a "standard"

```
python  -m pip install 'bezier==2020.5.19'
```

does not work for you? I.e. is there something wrong with the wheels for Python 3.9 on Windows 10?
