### ISSUE TITLE
Build libbezier with setup.py

### ISSUE THREAD

**Issue by Cilyan** [dhermes/bezier#283]
I currently have issues building bezier, both using pip because it complains that `BEZIER_INSTALL_PREFIX` is not defined, and also manually: building the lib with CMake is fine, but then the `setup.py` script doesn't seem to build properly, even providing `BEZIER_INSTALL_PREFIX`.

And I was wondering why the compilation of this companion lib isn't handled by setuptools like it is with SciPy for example? (no criticism there, just an interested question/suggestion and possibly gathering of previous experiences before I give it a try myself)

**Comment by dhermes** [comment]
Thanks for filing the issue @Cilyan. Are you using Python 3.10? I haven't cut a release of `bezier` since Python 3.10 was released, so there are no pre-built wheels for 3.10.

----

If you want to install pure-Python without the extension, follow the docs https://bezier.readthedocs.io/en/2021.2.12/#installing:

```
BEZIER_NO_EXTENSION=true \
  python  -m pip install --upgrade bezier --no-binary=bezier
```

----

If you want to install **with** the binary extension (i.e. with `cmake` as you mentioned), from the dev docs https://bezier.readthedocs.io/en/2021.2.12/development.html#libbezier:

```
SRC_DIR="src/fortran/"
BUILD_DIR=".../libbezier-debug/build"
INSTALL_PREFIX=".../libbezier-debug/usr"
mkdir -p "${BUILD_DIR}"
cmake \
  -DCMAKE_BUILD_TYPE=Debug \
  -DCMAKE_INSTALL_PREFIX:PATH="${INSTALL_PREFIX}" \
  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
  -S "${SRC_DIR}" \
  -B "${BUILD_DIR}"
cmake \
  --build "${BUILD_DIR}" \
  --config Debug \
  --target install
```

then you can run

```
BEZIER_INSTALL_PREFIX="${INSTALL_PREFIX}" python  -m pip install bezier
```

----

If 3.10 is your issue, you can follow #273, which I'll close out once I've actually cut a new release.

----

I am going to pre-emptively close this issue because I hope I've given a path forward and an explanation about the current state of packaging. If not, let me know and we can re-open this ticket.

**Comment by Cilyan** [comment]
Sorry, I wasn't as clear as I intended. The question is more about the second part (the above was just to give some context). SciPy builds its Fortran lib with setup.py and numpy used to do it (IIRC, they don't have Fortran code anymore except in their tests), but they still have a C library to compile with setuptools. Both also have Cython code that they generate and build during setup.py build_ext. So this is my question, is there any motivation not to do the same?

**Comment by dhermes** [comment]
Yes I used to do this as well; I don't think it's worth the effort. Building with CMake and setting the `BEZIER_INSTALL_PREFIX` environment variables is well documented and straightforward. Additionally, building from source **without** speedups is also well documented.

That said, maybe I should just disable speedups by default during build (i.e. make them opt-in during build instead of opt-out).

**Comment by dhermes** [comment]
> Both also have Cython code that they generate and build during setup.py build_ext

The Cython code is compiled and the generated `.c` file is checked in during development time. From https://cython.readthedocs.io/en/latest/src/userguide/source_files_and_compilation.html#distributing-cython-modules

> It is strongly recommended that you distribute the generated `.c` files as well as your Cython sources, so that users can install your module without needing to have Cython available.

**Comment by Cilyan** [comment]
The problem with a multi-steps manual build is that the library doesn't integrate well into typical environment management tools, like the requirements.txt or pipenv, poetry, hatch, ... Whenever none of the available wheels are suitable for the environment, the project setup is going to break, which rules out the library as a good candidate for integration.

**Comment by dhermes** [comment]
Yeah I am legitimately considering just installing without the speedups. I'd imagine it's impossible to please everyone here:

> **Without speedups**: We didn't know we were running without speedups. We wish the install had failed and notified us so that our code wasn't slow without us directly knowing.
> **With speedups**: We want to be able to install without a failure or configuration, even if that means silently degrading performance.

I will think about this some more before making a decision.

**Comment by Cilyan** [comment]
Using the extensions provided by numpy, I was able to create a minimal `setup.py` that builds the Fortran+C code as a unique python `_speedup` module. This covers probably only a small portion of the setup tricks you built over the years, but still I was surprised by how short it can be, especially as I was first looking at how SciPy does it, and theirs is way more complex.

If we can keep it small, maybe this could act as your "backup", instead of having to decide between with or without speedups by default ? Here is the script for reference:

```python
import os
from numpy.distutils.core import setup
from numpy.distutils.extension import Extension
from numpy import get_include

VERSION = "2021.2.13.dev1"  # Also in ``codemeta.json`` and ``__init__.py``.
AUTHOR = "Danny Hermes"  # Also in ``__init__.py``.
DESCRIPTION = (
    "Helper for B\u00e9zier Curves, Triangles, and Higher Order Objects"
)

libbezier = (
    'bezier',
    {
        'sources': [
            'src/fortran/types.f90',
            'src/fortran/status.f90',
            'src/fortran/helpers.f90',
            'src/fortran/quadpack.f90',
            'src/fortran/curve.f90',
            'src/fortran/curve_intersection.f90',
            'src/fortran/triangle.f90',
            'src/fortran/triangle_intersection.f90',
        ],
    }
)

ext_speedup = Extension(
    "bezier._speedup",
    sources=["src/python/bezier/_speedup.c"],
    include_dirs=[
        get_include(),
        "src/fortran/include",
    ],
    libraries=[libbezier]
)

setup(
    name="bezier",
    version=VERSION,
    description=DESCRIPTION,
    author=AUTHOR,
    author_email="daniel.j.hermes@gmail.com",
    url="https://github.com/dhermes/bezier",
    project_urls={
        "Documentation": "https://bezier.readthedocs.io/",
        "Changelog": (
            "https://bezier.readthedocs.io/en/latest/releases/index.html"
        ),
        "Issue Tracker": "https://github.com/dhermes/bezier/issues",
    },
    keywords=["Geometry", "Curve", "Bezier", "Intersection", "Python"],
    packages=["bezier", "bezier.hazmat"],
    package_dir={
        "": "src/python"
    },
    ext_modules = [ext_speedup],
    install_requires=['numpy>=1.21.4'],
    extra_require={
        "full": ["matplotlib >= 3.4.3", "scipy >= 1.7.2", "sympy >= 1.9"],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "Topic :: Scientific/Engineering :: Mathematics",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: Implementation :: CPython",
        "Programming Language :: Python :: Implementation :: PyPy",
    ],
)
```

**Comment by dhermes** [comment]
@Cilyan I **really** appreciate the effort but explicitly do not want that path forward. That was the approach this project used to use and it was an unmaintainable mess. Supporting multiple architectures and operating systems is very painful, which is why I sought out CMake (a build tool that is explicitly multi-platform and explicitly supports building Fortran shared libraries).

I am planning on collaborating with @henryiii in 2022 to pilot `scikit-build` to utilize CMake in a more Python-native way. Hopefully this will address some of your concerns.

----

If you're curious about some of the history, see e.g. https://github.com/dhermes/bezier/blob/2020.1.14/setup_helpers_windows.py as well as https://github.com/dhermes/bezier/releases/tag/2020.2.3, the release where the custom Python hacks stopped being worth it.

**Comment by Cilyan** [comment]
I had checked indeed the commits when you still used setuptools, but it's hard to figure out all the work that went into it just looking at the files and a bit of history. IMHO, whatever the underlying mechanism, the most important is that in the end it's just a `pip install bezier` away from the user, and it's currently not the case (actually, if it was, I wouldn't have even bothered you :) ). If this is achieved with scikit-build, then that's a good move (not in 3 years I hope).

CMake has its drawbacks too, there are reasons why many projects (and that's our case) moved away from it. My feelings are that it suffers from the same issues you point out with `distutils`/`setuptools`. From the outside it looks more polished and does a great job at simple tasks, but it abstracts away the underlying mechanisms so much that whenever you slightly drift away from the "standard usage", it becomes a nightmare to adapt all these layers to your needs. (`docutils` is a bit like that too in its own domain... Never name your project `...utils`, it's cursed!)

I wish you good luck anyway.
